### ISSUE TITLE
我想问下 如何使用webpack-spritesmith打包雪碧图呢

### ISSUE THREAD

**Issue by geekmakersun** [APIS-X/Webpack5-MPA#1]
<link rel="stylesheet" href="assets/sprite/sprite.css">
build 打包后 css可以引用 dev加载不出来

**Comment by geekmakersun** [comment]
webpack-dev-server  搜索引擎查询到的结果 “实时编译后的文件都保存到了内存当中”  这个问题不知道该怎么解决

**Comment by APIS-X** [comment]
> build 打包后 css可以引用 dev加载不出来

应该是路径设置有问题，可参见https://gitee.com/APIS-X/webpack5-MPA

**Comment by APIS-X** [comment]
@GeekMakerSun  应该是路径设置有问题，可参见https://gitee.com/APIS-X/webpack5-MPA

**Comment by APIS-X** [comment]
@GeekMakerSun ’webpack-dev-server 搜索引擎查询到的结果 “实时编译后的文件都保存到了内存当中” 这个问题不知道该怎么解决‘这个问题不用解决，前端项目本地跑的时候本来实时编译的文件本来就是存在内存中
